service: default
runtime: python37
instance_class: F1
env: standard
automatic_scaling:
  min_instances: 1
  max_instances: 2
  max_idle_instances: 1
  target_cpu_utilization: 0.85
  max_concurrent_requests: 80
  max_pending_latency: 6s
default_expiration: "1m"

inbound_services:
- warmup

handlers:
  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301

entrypoint: gunicorn -b 0.0.0.0:8080 main:server